### PR TITLE
Latest Update

### PR DESCRIPTION
**Pull request by Rashotech**
I have added new executives information and pictures. I have also fixed some bugs. I also created new pages: programs and gallery. Newsletter Functionality has also been added.

### CODE REVIEW

**Comment by AbdullahiAbdulkabir** [comment]
Nice work here. This will work however this is not the branch I said you should start working from. You should start working from the develop branch and send a pull request against that branch.

**Comment by AbdullahiAbdulkabir** [comment]
If I merge this I will still need to generate the assets which has been done in the develop branch @Rashotech

**Comment by Rashotech** [comment]
I deliberately created the new dev branch. the develop branch was not running on my local machine and the required files are missing there. I believe that in this new branch the asset are already there. I created this dev branch from the master branch.

**Comment by AbdullahiAbdulkabir** [comment]
How did you setup the project locally? You used jeykll?
I know you created a Dev branch but the develop branch is just an html and CSS how are you not able to set it up?

**Comment by Rashotech** [comment]
I used Jekyll to run the dev branch locally. I didn't know that the develop branch is just pure html and css because I saw gem file in the branch so I tried to used jekyll to run it and it didn't work.

**Comment by AbdullahiAbdulkabir** [comment]
Oh nice, I am happy, there is a last step you need to do.
You need to generate the html files

**Comment by AbdullahiAbdulkabir** [comment]
Use `jekyll build` and it's going to generate a static files inside _site push that folder along side that what I will need majorly to deploy 
Here for reference: https://jekyllrb.com/docs/usage/

**Comment by Rashotech** [comment]
I would run the Jekyll build command to generate the html to _site. I would do that before the end of today. I would let you when am done so that you can merge and deploy.

**Comment by Rashotech** [comment]
I have generated the html..you can now merge and deploy

**Pull request merged**
